export const FETCH_FILES_LIST_REQUEST = "FETCH_FILES_LIST_REQUEST";
export const FETCH_FILES_LIST_SUCCESS = "FETCH_FILES_LIST_SUCCESS";
export const FETCH_FILES_LIST_FAILURE = "FETCH_FILES_LIST_FAILURE";

export const FETCH_FILES_DATA_REQUEST = "FETCH_FILES_DATA_REQUEST";
export const FETCH_FILES_DATA_SUCCESS = "FETCH_FILES_DATA_SUCCESS";
export const FETCH_FILES_DATA_FAILURE = "FETCH_FILES_DATA_FAILURE";

export const SET_SELECTED_FILE = "SET_SELECTED_FILE";
